################################################################################
# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node.
#
# For more information see:
#
#   https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
################################################################################

name: Node.js CI

# Controls when the action will run. Triggers the workflow on push or pull
# request events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            node-version: 18
          - os: ubuntu-22.04
            node-version: 20

    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
      - name: Build environment information
        run: 'echo "Matrix OS: ${{ matrix.os }} on $HOSTNAME with $(getconf _NPROCESSORS_ONLN) cores"'

        # Check-out the repository under $GITHUB_WORKSPACE, so the job can
        # access it
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore node modules
        id: restore-node
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-install-${{ matrix.node-version }}-${{ hashFiles('package.json', 'yarn.lock') }}

      - name: yarn install
        if: steps.restore-node.outputs.cache-hit != 'true'
        run: yarn install

      - name: yarn audit-ci
        run: yarn audit-ci

      # TODO
      #- name: yarn lint
      #  run: yarn lint

      - name: Restore OpenCV library
        id: restore-opencv
        uses: actions/cache@v2
        with:
          path: |
            tools/dist
          key: restore-opencv-${{ matrix.os }}-${{ hashFiles('tools/depends/ade/*', 'tools/depends/ceres-solver/*', 'tools/depends/eigen/*', 'tools/depends/emscripten/*', 'tools/depends/google-flags/*', 'tools/depends/google-log/*', 'tools/depends/opencv/*') }}

      - name: Restore C++ libraries
        id: restore-libraries
        uses: actions/cache@v2
        with:
          path: |
            public/motion_tracker/motion_tracker.js
            public/motion_tracker/motion_tracker.wasm
          key: restore-libraries-${{ matrix.os }}-${{ hashFiles('lib/**', 'tools/depends/ade/*', 'tools/depends/ceres-solver/*', 'tools/depends/eigen/*', 'tools/depends/emscripten/*', 'tools/depends/google-flags/*', 'tools/depends/google-log/*', 'tools/depends/opencv/*') }}

      - name: Restore dependency libraries
        id: restore-library-depends
        uses: actions/cache@v2
        if: steps.restore-opencv.outputs.cache-hit != 'true'
        with:
          path: |
            tools/dist
          key: restore-library-depends-${{ matrix.os }}-${{ hashFiles('tools/depends/ade/*', 'tools/depends/ceres-solver/*', 'tools/depends/eigen/*', 'tools/depends/emscripten/*', 'tools/depends/google-flags/*', 'tools/depends/google-log/*', 'tools/depends/opencv/*') }}

      - name: Build depends
        if: steps.restore-libraries.outputs.cache-hit != 'true' || steps.restore-opencv.outputs.cache-hit != 'true'
        run: yarn depends

      - name: yarn test
        run: yarn test

      - name: yarn build
        run: yarn build
